### ISSUE TITLE
Normalize auto generated class name.

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.upgrade#102]
e.g. when I type `bin/upgrade create "Add test.xml file"` the resulting class name in `upgrade.py` will be `AddTest.xml` which is not a valid python class name. So a normalized string would be nice.

**Comment by mbaechtold** [comment]
What about:

```
>>> ''.join(x for x in 'Add test.xml file'.title() if x.isalpha())
'AddTestXmlFile'
```

**Comment by jone** [comment]
We're using [inflection](https://pypi.python.org/pypi/inflection) for that already.
The generated directory-name is also not correct..
