### ISSUE TITLE
ftw.upgrade causes backtrace when importing GS tarballs in the ZMI portal_setup

### ISSUE THREAD

**Issue by fredvd** [4teamwork/ftw.upgrade#120]
While I was experimenting with pas.plugins.ldap and its GS profile, ldapsetings.xml, I tried to re-imported a just before exported GS tarball (exported with only the ldap settings as a selected export step) in the ZMI. This caused the following backtrace:

```
* Module ZPublisher.Publish, line 138, in publish
* Module ZPublisher.mapply, line 77, in mapply
* Module ZPublisher.Publish, line 48, in call_object
* Module Products.GenericSetup.tool, line 606, in manage_importTarball
* Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
* Module Products.GenericSetup.tool, line 1424, in _runImportStepsFromContext
* Module zope.event, line 31, in notify
* Module zope.component.event, line 24, in dispatch
* Module zope.component._api, line 136, in subscribers
* Module zope.component.registry, line 321, in subscribers
* Module zope.interface.adapter, line 585, in subscribers
* Module ftw.upgrade.directory.subscribers, line 10, in profile_installed
* Module re, line 155, in sub
TypeError: expected string or buffer
```

This is without ftw.upgrade being installed in the Plone site, but only listed in the buildout:eggs. After removing ftw.upgrade from the installed eggs, the same GS tarball imported succesfully without a backtrace.

**Comment by jone** [comment]
@fredvd I've implemented a fix in https://github.com/4teamwork/ftw.upgrade/pull/121
Can you test if it works with that fix?

**Comment by fredvd** [comment]
@jone Yes this solves the backtrace, added the same two lines in the project, re-added ftw.upgrade and I can import the tarball now.

**Comment by jone** [comment]
@fredvd thanks! I've released `ftw.upgrade = 2.1.1` with the fix 😉
