### ISSUE TITLE
Log current item in ProcessLogger if logger exits unexpectedly

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.upgrade#135]
If an upgrade-step fails on a specific item there is currently no way to tell which item exactly caused the error. You have the stack-trace and a rough number where the error occurred but no exact location:
```
2017-04-26 09:40:02 INFO ftw.upgrade 6632 of 7992 (82%): Move File to ListingBlock
2017-04-26 09:40:07 INFO ftw.upgrade 6650 of 7992 (83%): Move File to ListingBlock
2017-04-26 09:40:10 ERROR ftw.upgrade FAILED Move File to ListingBlock (GeneratorExit: )
2017-04-26 09:40:10 ERROR ftw.upgrade FAILED
```

This is only a problem with long running upgrade-steps. And as the ProgressLogger is especially designed to be used with those upgrades i think this feature would be a great addition.

https://github.com/4teamwork/ftw.upgrade/blob/master/ftw/upgrade/progresslogger.py#L39

@jone What do you think? Is this the correct place to add such a feature?

**Comment by jone** [comment]
Yes, that would be awesome 👍 
Be aware that `self.iterable` may be a generator which does not allow item access.
The easiest would be to store the item in `self.current_item` before [yielding it in `__iter__`](https://github.com/4teamwork/ftw.upgrade/blob/master/ftw/upgrade/progresslogger.py#L61), and then log with `repr(self.current_item)`.
Be also aware that the item may not be a Plone object. It could be any type of object, even strings or numbers.
