### ISSUE TITLE
"update_security_for" should not be executed recursively

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.upgrade#151]
Given a structure of same-kind folderish objects:
```
- A
  - B
    - C
```

When `update_security_for` is called for all objects of a kind, this may be recursive and certain children are updated multiple times, e.g.:

=> A, b, c, B, c, C

This is very inefficient.

We should implement our own `reindexObjectSecurity` as helper function which is less stupid, optimized for our case.

**Comment by flipmcf** [comment]
I saw this too.... I was under the impression that 'reindexObjectSecurity' was supposed to be really bulletproof security wise at the expense of being inefficient.    I could be wrong.
