### ISSUE TITLE
Add deferreable upgrades.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/ftw.upgrade#165]
We want to tag upgrade as deferrable but to still propose them by default.

As described in https://github.com/4teamwork/opengever.core/issues/4150 sometimes our upgrades are long running but do not need to be executed at the exact same time as the code changes (a fix-script for example that migrates data). We still want a mechanism to register these upgrades and to track if they have been installed/run already. Also this helps to couple the code of said fix-script close to the actual bugfix made in the code, best would be if the they can be provided in the same pull-request.

The following things should be taken care of:
- add possibility to mark upgrades as deferrable (class-attribute, for example)
- propose deferrable upgrades by default
- make deferrable upgrades visible in `bin/upgrade`
- make deferrable upgrades visible in `@@manage-upgrades`
- amend upgrade command with option to skip deferrable upgrades `-D`
- ~~amend upgrade command with option to execute only deferred upgrades (should abort if non-deferred upgrades are found) `--deferred-only, -D`~~

**Comment by deiferni** [comment]
After a discussion with @lukasgraf and @phgross we have decided to slightly change the implementation and how it behaves by default. Instead of calling the upgrade `deferred` and omitting it by default we will now call it `deferrable` and install it by default.

advantages:
- prevent that upgrades are not run and lie around indefinitely, especially with our current tooling around `update_deployment`.
- easier workflow for small deployments where the deferred/deferrable upgrade will be be run together with the other upgrades (transactionality, simpler path). no extra action has to be taken when upgrading those. for larger deployments we always take extra care with the upgrade-path, we will still have the option to omit deferred upgrades then.

_(issue has been rewritten)_

**Comment by jone** [comment]
Makse absolutely sense 👍
