### ISSUE TITLE
Plone 5.2, Python 3?

### ISSUE THREAD

**Issue by mauritsvanrees** [4teamwork/ftw.upgrade#195]
I tried ftw.upgrade on Plone 5.2 and it does not quite work.
With Python 2.7 and a running instance (either standalone or zeo):

```
$ bin/upgrade sites
ERROR: No running Plone instance detected.
```

With Python 3 I get lots of `SyntaxErrors` while running buildout, mostly for print statements and old-style exceptions. Later followed a version conflict, although that may easily be because of some version pins by me:

```
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('-', parent)?

  File "/Users/maurits/shared-eggs/cp36m/tmpzbnd0u95/ftw.upgrade-2.16.0-py3.6.egg/ftw/upgrade/command/user.py", line 32
    print 'Authenticated as "{0}".'.format(response.json())
                                  ^
SyntaxError: invalid syntax

  File "/Users/maurits/shared-eggs/cp36m/tmpzbnd0u95/ftw.upgrade-2.16.0-py3.6.egg/ftw/upgrade/jsonapi/plonesite.py", line 192
    except Exception, exc:
                    ^
SyntaxError: invalid syntax

Got ftw.upgrade 2.16.0.
Getting distribution for 'tarjan'.
Got tarjan 0.2.3.2.
Getting distribution for 'path.py>=6.2'.
Got path.py 12.4.0.
Getting distribution for 'inflection'.
Got inflection 0.3.1.
Getting distribution for 'argparse'.
Got argparse 1.4.0.
Getting distribution for 'argcomplete'.
Got argcomplete 1.11.1.
Getting distribution for 'path<13.2'.
Got path 13.1.0.
Version and requirements information containing importlib-metadata:
  [versions] constraint on importlib-metadata: 0.18
  Requirement of argcomplete: importlib-metadata<2,>=0.23
  Requirement of path<13.2: importlib-metadata>=0.5
While:
  Installing zeoclient.
Error: The requirement ('importlib-metadata<2,>=0.23') is not allowed by your [versions] constraint (0.18)
```

Do you have plans for supporting Plone 5.2?
And Python 3?
Any rough timeframe for that?

**Comment by mauritsvanrees** [comment]
For Python 3, the steps on [docs.plone.org](https://docs.plone.org/manage/upgrading/version_specific_migration/upgrade_to_python3.html) should help. Either you or I could do the basis: use python-modernise and six to get basic compatibility so there are at least no syntax errors.

With Plone 5.2 on Python 2.7, I see the first problem is that `bin/upgrade` looks for a port number in `zope.conf`. With 5.2 it should look in `wsgi.ini`. I will make a PR to do both.

Next problem is that `portal_css` is not found, so `cook_resources` fails. That code should probably silently do nothing when the tool is not found. I will try.

**Comment by mauritsvanrees** [comment]
For Python 3, I see that @buchi has already started on a [branch](https://github.com/4teamwork/ftw.upgrade/tree/python3).

**Comment by maethu** [comment]
@mauritsvanrees Thanks for helping here. We definitely have the goal to make ftw.upgrade Plone 5.2 and Python 3 compatible. 
@buchi What's the current state of your branch?

**Comment by buchi** [comment]
The branch already includes a lot of fixes, but there's still some work left.
Didn't have much time recently, but I can give it a try in the next days.
Mostly it's about quickinstaller stuff (API changes and functionality that has been removed).
So far I've only tried to get the tests to pass.

**Comment by buchi** [comment]
New version 3.0.0 with support for Plone 5.2 and Python 3 was released.
