### ISSUE TITLE
Make "six" a direct dependency

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.upgrade#198]
This Plone addon makes use of `six` a lot, but it is not declared as a direct dependency in `setup.py`.

I propose to add it to the `setup.py` and require at least 1.12.0 because this code base uses `six.ensure_text` which was added only in 1.12.0 (see  `https://github.com/benjaminp/six/blob/3a3db7510b33eb22c63ad94bc735a9032949249f/CHANGES#L39).

This will solve the failing test setup of other software packages making use of `ftw.upgrade` but having an older version of `six`.

@buchi, what do you think about this issue?

**Comment by mauritsvanrees** [comment]
:+1.
PR merged, issue can be closed.

**Comment by buchi** [comment]
Yep, `six >= 1.12.0` should be added to `install_requires`.

However this will not solve issues with setups that pin an older version of six. Buildout will just fail with a bad constraint error. You will have to bump your version pin anyway.

**Comment by mbaechtold** [comment]
I'm reopening this issue because the corresponding pull request https://github.com/4teamwork/ftw.upgrade/pull/199 has not been merged yet.

**Comment by mbaechtold** [comment]
But as I'm working through my GitHub notifications, I just noticed that the pull request has been approved by @maethu. I have merged the pull request and this issue has bene closed automatically.
