### ISSUE TITLE
Purge resource registries

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.upgrade#70]
After an upgrade is installed, there should be a way to easily invalidate the resource registry bundles in `portal_css` and `portal_javascripts`.

Options:

1) Automatically purge resource registries when upgrades are executed (for both, `@@manage-upgrades` and `bin/upgrade execute*`)

2) Automatically purge resource registries when upgrades are installed by script (`bin/upgrade execute*`)

3) Provide a JSON-API endpoint and a command for purging resource registries (`bin/upgrade purge-resource-registries`)

@lukasgraf @maethu @deiferni what do you think?

**Comment by lukasgraf** [comment]
:+1: !

**Comment by deiferni** [comment]
hmm sounds like something you'd like to do all the time - so i would probably go with 1). This would also solve problems with flawed upgrades that do not recook registries. Or does anyone see a potential problem with such an approach?

**Comment by jone** [comment]
I've done a little test: when adding a new CSS resource, the registry is recooked automatically.

I think 3) is quite important, since we don't necessarily run upgrade steps when the CSS files are changed and might want to trigger recooking. Especially with [git deployment](https://github.com/4teamwork/plone-git-deployment) :wink:
