### ISSUE TITLE
Missing dependency with version 1.13.0

### ISSUE THREAD

**Issue by marfago** [4teamwork/ftw.upgrade#71]
I've just rebuilt a plone site and now I have this error:

ZopeXMLConfigurationError: File "/Plone-Dev/eggs/ftw.upgrade-1.13.0-py2.7.egg/ftw/upgrade/jsonapi/configure.zcml", line 5.4-16.10
    ImportError: No module named _curses

I had no issues with previous versions.

**Comment by jone** [comment]
Since `1.12.0` we have an extended `bin/upgrade` command which uses [blessed](https://github.com/jquast/blessed) for terminal output.
`blessed` is a wrapper around [curses](https://docs.python.org/2/library/curses.html), which is a python standard library module.

It seems that your Python build is missing the bindings.

Maybe the [UniCurses](https://pypi.python.org/pypi/UniCurses) package could help.
Could you try to add `UniCurses` to your eggs list and try if it works?
If it works I'll add it as dependency to ftw.upgrade.

**Comment by lukasgraf** [comment]
@jone I'm not sure UniCurses will help here - I don't think it's a drop-in replacement for the `_curses` module, so unless `blessed` somehow falls back on it it likely won't work.

@marfago what Linux distribution are you using?

It looks like the `*.h` header files for `libncurses` were missing on your system when you built Python, so Python was unable to build the `_curses` module.

On Debian based distributions the development headers should be in a package called `libncurses5-dev`,   on RedHat based distros it should be `ncurses-devel`. After installing those headers you would need to recompile Python unfortunately.

We should probably make any imports of `blessed` conditional, and fall back to a plain boring output if it can't be imported.

**Comment by marfago** [comment]
Here it is:

Linux version 3.13.0-44-generic (buildd@lamiak) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014

Anyway, Im not very expert with python, can you show me hw to install the curses library?
I tried with pip but with success.

Thank you.

**Comment by lukasgraf** [comment]
The standard Python on Ubuntu should include curses support. Are you using a Python you compiled yourself?

**Comment by marfago** [comment]
I'm using the standard version. I have not recompiled it.

**Comment by lukasgraf** [comment]
I would suggest you try installing the `libncurses5-dev` package and re-installing Python (both using `apt-get`).

**Comment by jone** [comment]
@marfago I've just released `ftw.upgrade = 1.14.0`, which includes a fix for your problem.
It would be great if you could test it and give us feedback :wink:

**Comment by marfago** [comment]
It now works. Thank you.
Marco
