### ISSUE TITLE
blessed constraint problems

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.upgrade#87]
The ftw.upgrade dependency "blessed" latest release 1.10.0 is not compatible with Plone 4.3.x blessed requires six >= 1.9.0, Plone pins 1.8.0.

I think we should get rid of the `blessed` dependency and replace it with another terminal library.

See also: https://github.com/4teamwork/ftw-buildouts/blob/master/test-versions.cfg#L19-L21

**Comment by lukasgraf** [comment]
I think there's also two other options we could consider here:

- Do any of the terminal stuff we need ourselves. As far as I can tell, it's really just colorization and calculating the length of strings with terminal sequences in them that we need, length calculation being the tricky part. (`ljust()`, `center()`, `wrap()`, etc. basically all boil down to length calculation). If we limit support to basically just ANSI color sequences, the length calculation should be much simpler than [what's being done in `blessed`](https://github.com/jquast/blessed/blob/18e1d0008ece8d4d5da117e24b7dd1137ed43d0c/blessed/sequences.py#L558).

- Vendorize either `blessed` or a simpler terminal library, similar to what the [`requests` module does with the `urllib3` and `chardet` libraries](https://github.com/kennethreitz/requests/tree/master/requests/packages). In my experience, this works pretty well if done right.
