### ISSUE TITLE
bin/upgrade finds running instances using hardcoded instance*

### ISSUE THREAD

**Issue by fredvd** [4teamwork/ftw.upgrade#91]
According to "bin/upgrade help":

    The Zope instance is discovered automatically by searching for all
    "zope.conf" files in "parts/instance*" of the buildout directory, looking
    up the instance port and testing whether the port is bound on localhost.

In our buildouts we use 'zeoclient' as the instance name in a zeoclient/zeoserver setup.

Can we somehow change this hardcoded search for instance* using a parameter for bin/upgrade or otherwise add a URL parameter for bin/upgrade to specify the instance to which to connect?

**Comment by jone** [comment]
Maybe it would be better to do something like `find parts -name zope.conf`, this would work well in our installations. Expecting a name isn't good anyways. And it would be great if it just works without configuration..

**Comment by jone** [comment]
@fredvd I've release `ftw.upgrade = 1.15.1` with a fix :wink:
